---
galaxy_info:
  author: ome-devel@lists.openmicroscopy.org.uk
  description: Install Java JREs and optionally JDKs.
  company: Open Microscopy Environment
  license: BSD
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
  categories:
    - system
