---

- name: Pulling projects
  # become: "{{ item.user | default('root') }}"
  become_user: "{{ item.user | default('root') }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dir }}"
    version: "{{ item.version | default('HEAD') }}"
    accept_hostkey: yes
  with_items: "{{ deploy_projects }}"
  tags:
    - deploy