---
- hosts: all
  become: yes
  become_user: root
  # remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: yes
    docker_channel: "stable"
    docker_version: "18.03.0"

  roles:
    # - local-debug
    # - base
    # - { role: docker-install, tags: docker-install }
    - deploy
    # - docker-confs
    # - docker-nginx
    # - docker-compose