version: '3.6'

services:

  # ---------------------------------------------------------------------------
  # Postgres
  # ---------------------------------------------------------------------------

  postgres:
    container_name: aiseal-postgres
    image: postgres:latest
    ports:
      - 54320:5432
    volumes:
      - ./containers/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./containers/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./containers/postgres/.env

  # ---------------------------------------------------------------------------
  # Redis
  # ---------------------------------------------------------------------------

  redis:
    container_name: aiseal-redis
    restart: always
    image: redis:latest
    ports:
      - 63790:6379

  # ---------------------------------------------------------------------------
  # Microservices
  # ---------------------------------------------------------------------------

  # Heimdall (12/07/2018 11:03 - Deepak Vashist)
  # User and authentication/authorization microservice
  heimdall:
    container_name: heimdall
    restart: always
    build:
      context: ./projects/heimdall
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ./containers/postgres/.env
    volumes:
      - ./projects/heimdall:/usr/src/app
      - ./containers/scripts:/usr/src/docker_scripts
    command: bash -c "/usr/src/docker_scripts/wait-for-postgres.sh postgres python /usr/src/app/src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  # Chronos (18/07/2018 11:45 - Deepak Vashist)
  # Users schedules, events, important dates...
  chronos:
    container_name: chronos
    restart: always
    build:
      context: ./projects/chronos
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ./containers/postgres/.env
    volumes:
      - ./projects/chronos:/usr/src/app
      - ./containers/scripts:/usr/src/docker_scripts
    command: bash -c "/usr/src/docker_scripts/wait-for-postgres.sh postgres python /usr/src/app/src/manage.py runserver 0.0.0.0:8001"
    depends_on:
      - postgres

  # Brö (22/07/2018 14:14 - Deepak Vashist)
  # Brö CORE modelue
  bro:
    container_name: bro
    restart: always
    build:
      context: ./projects/bro
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ./containers/postgres/.env
    volumes:
      - ./projects/bro:/usr/src/app
      - ./containers/scripts:/usr/src/docker_scripts
    command: bash -c "/usr/src/docker_scripts/wait-for-postgres.sh postgres python /usr/src/app/src/manage.py runserver 0.0.0.0:8002"
    depends_on:
      - postgres
