version: '3.6'

services:
  # ---------------------------------------------------------------------------
  # Postgres
  # ---------------------------------------------------------------------------
  postgres:
    container_name: aiseal-postgres
    image: postgres:latest
    ports:
      - 54320:5432
    volumes:
      - ./containers/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./containers/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./containers/postgres/.env

  # ---------------------------------------------------------------------------
  # Redis
  # ---------------------------------------------------------------------------
  redis:
    container_name: aiseal-redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379

  # ---------------------------------------------------------------------------
  # Microservices
  # ---------------------------------------------------------------------------

  # Heimdall (12/07/2018 11:03 - Deepak Vashist)
  # User and authentication/authorization microservice
  heimdall:
    container_name: heimdall
    restart: always
    build:
      context: ./projects/heimdall
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./projects/heimdall:/usr/src/app
      - ./containers/scripts:/usr/src/docker_scripts
    command: bash -c "./docker_scripts/wait-for-postgres.sh postgres python ./app/manage.py runserver 0:8000"
    depends_on:
      - postgres
