version: '3.6'

services:
  postgres:
    restart: always
    image: postgres:latest
    # healthcheck:  # nao suportado mais a partir da versão 3 do dokercompose file
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 3s
    #   timeout: 30s
    #   retries: 3
    # volumes_from:
    #   - data
    volumes:
      - ./containers/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./backups/postgresql:/backup
      - ./pgdata:/var/lib/postgresql/data/
    env_file:
      - env
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  project1:
    container_name: project1-app
    restart: always
    build: ./projects/project1/
    # expose:
    #   - "8000"
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file: env

    volumes:
      - ./projects/project1:/usr/src/app
      - ./containers/scripts:/usr/src/docker_scripts
    working_dir: /usr/src/
    # para entender o pq do arquivo ./wait-for-postgres.sh => https://docs.docker.com/compose/startup-order/
    command: bash -c "./docker_scripts/wait-for-postgres.sh postgres python ./app/manage.py runserver 0:8000"
    depends_on:
      - postgres