---
# tasks file for base
- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items:
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - "{{ base_python_package }}-pip"
    - supervisor
  tags:
    - packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages