version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./containers/nginx
    ports:
      - 80:80
    volumes:
      - ./confs/nginx/conf.d/apps/:/etc/nginx/conf.d/apps/
      - ./confs/nginx/nginx.conf:/etc/nginx/nginx.conf
    # nao precisava, pois o docker-compose busca um arquivo com o nome de .env
    # no mesmo diretorio, mas coloquei apenas para ficar explicito
    # env_file:
    #   - .env
    # networks:
    #   public_net:
    #     ipv4_address: ${NGINX_IP}

  # app:
  #   container_name: app_teste
  #   build:
  #       context: .
  #   ports:
  #     - 8000:8000
  #   # env_file:
  #   #   - ./containers/postgres/.env
  #   volumes:
  #     - /srv/chronos:/usr/src/app
  #   command: bash -c "python /usr/src/app/src/manage.py runserver 0.0.0.0:8000"

# networks:
#     public_net:
#         driver: bridge
#         ipam:
#             driver: default
#             config:
#                 - subnet: ${NETWORK_SUBNET}