---
# tasks git pull

- name: Copying SSH public key file
  copy: src="{{ playbook_dir }}/../ssh-key/id_rsa.pub"
        dest="/root/.ssh/id_rsa.pub"
        mode=0644

- name: Copying SSH private key file
  copy: src="{{ playbook_dir }}/../ssh-key/id_rsa"
        dest="/root/.ssh/id_rsa"
        mode=0600

- name: Creating project "{{ local_project_folder_name }}" directory
  file: path={{ remote_project_dir }}
        state=directory
  tags:
    - deploy

- name: Git pull project "{{ local_project_folder_name }}" from git
  git:
    repo: "ssh://git@bitbucket.org:/aisealteam/chronos.git"
    dest: "{{ remote_project_dir }}"
    # accept_hostkey: True
    # key_file: "{{ playbook_dir }}/../ssh-key/id_rsa"
  tags:
    - deploy

- name: Copying content .env.production to .env production file
  copy:
    src: "{{ remote_project_dir }}/src/.env.production"
    dest: "{{ remote_project_dir }}/src/.env"
    remote_src: yes
  tags:
    - deploy

- name: Copy docker-compose-production.yml content to docker-compose.yml file
  copy:
    src: "{{ remote_project_dir }}/docker-compose-production.yml"
    dest: "{{ remote_project_dir }}/docker-compose.yml"
    remote_src: yes
  tags:
    - deploy

# cd {{ remote_project_dir }} && docker-compose up -d --build
- name: Rebuild images defined in compose file and restart container {{ local_project_folder_name }} application
  command: docker-compose up -d --build
  args:
    chdir: "{{ remote_project_dir }}"
  tags:
    - deploy
