---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-jre
    image: centos:7
  - name: java-jdk
    image: centos:7
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      java-jdk:
        java_jdk_install: true

scenario:
  name: centos
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
